AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 150

# it would be great to use EnforcedStyle: semantic here but it complains way too much
Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ConditionalAssignment:
  Enabled: false
