require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - 'lib/tasks/cucumber.rake'
    - 'Guardfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_foundation.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 124

RSpec/DescribedClass:
  Enabled: false

# it would be great to use EnforcedStyle: semantic here but it complains way too much
Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: flase
