AllCops:
  RunRailsCops: true
#  DisplayCopNames: true
  Exclude:
    - 'lib/tasks/cucumber.rake'
    - 'Guardfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'config/unicorn.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_foundation.rb'
    - 'app/models/ability.rb'

Style/SignalException:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 16
Metrics/ClassLength:
  Max: 110
