require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 111

RSpec/DescribedClass:
  Enabled: false

# it would be great to use EnforcedStyle: semantic here but it complains way too much
Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false
