AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 150

# it would be great to use EnforcedStyle: semantic here but it complains way too much
Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "app/reports/**/*"
    - "config/**/*"
    - "**/*_spec.rb"
    - "spec/**/*"
    - 'lib/**/*'
    - 'features/**/*'

Rails/SkipsModelValidations:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Rails/FilePath:
  Exclude:
    - "spec/**/*"
    - "features/**/*"
    - "lib/tasks/*.rake"

Rails/OutputSafety:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false