# frozen_string_literal: true

return unless defined?(OpenTelemetry)

# Drops DB spans generated by Solid Queue/Solid Cable's internal polling
# loops -- these run on a fixed timer whether or not anyone is using the app
# (confirmed via Honeycomb: ~99.98% of daily span volume was
# SolidQueue::ReadyExecution/SolidCable::Message polling + the SELECT/BEGIN/
# COMMIT transaction spans those queries generate, not real traffic). Same
# "loop iteration -- unbounded, not interesting" case the otel-instrumentation
# skill itself calls out; dropped here rather than filtered at query time so
# it never costs ingest volume in the first place.
class PollingNoiseFilter
  NOISE_PATTERNS = [
    /solid_queue_ready_executions/,
    /solid_queue_recurring_executions/,
    /solid_queue_processes/,
    /solid_cable_messages/
  ].freeze

  def initialize(next_processor)
    @next_processor = next_processor
  end

  def on_start(span, parent_context)
    @next_processor.on_start(span, parent_context)
  end

  def on_finish(span)
    statement = span.attributes&.[]("db.statement")
    return if statement && NOISE_PATTERNS.any? { |pattern| pattern.match?(statement) }

    @next_processor.on_finish(span)
  end

  def force_flush(timeout: nil) = @next_processor.force_flush(timeout: timeout)
  def shutdown(timeout: nil) = @next_processor.shutdown(timeout: timeout)
end

# Honeycomb's model is query-first: wide events with full request context,
# sliced/grouped ad hoc after the fact (BubbleUp), not a pre-curated set of
# spans decided in advance. use_all auto-instruments every supported gem
# present (Rack, ActionPack, ActiveRecord/pg, ActionView, Net::HTTP, etc.) so
# that data is actually available to query later.
OpenTelemetry::SDK.configure do |c|
  c.service_name = "bakecycle-#{Rails.env}"
  c.use_all

  batch_processor = OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
    OpenTelemetry::Exporter::OTLP::Exporter.new
  )
  c.add_span_processor(PollingNoiseFilter.new(batch_processor))
end
