default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [file_exporter, default, payments, demo_creation]
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: [operations]
      threads: 1
      processes: <%= ENV.fetch("OPERATIONS_JOB_CONCURRENCY", 1) %>
      polling_interval: 1

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
